spring.application.name=RG_SGA_

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:postgresql://users_d4lc_user:BfKDP8DNoyhTyEQQ8jaBhh6ByjvMYCAH@dpg-d88kk06l51nc73fjmv70-a/users_d4lc}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:users_d4lc_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:BfKDP8DNoyhTyEQQ8jaBhh6ByjvMYCAH}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari Connection Pool Config
spring.datasource.hikari.maximum-pool-size=${HIKARI_MAX_POOL:10}
spring.datasource.hikari.minimum-idle=${HIKARI_MIN_IDLE:5}
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate-ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security Configurations
# Default key is a HS256-compatible random 256-bit key (64 hex characters)
application.security.jwt.secret-key=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# Expiration: 1 day in milliseconds (86400000)
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

server.port=8080



